-- ==========================================================
-- LAB 03: Khởi tạo bảng students & Dữ liệu mẫu (ANSI SQL)
-- ==========================================================

DROP TABLE IF EXISTS students;

CREATE TABLE students (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    age INT NOT NULL,
    email VARCHAR(100) NOT NULL,
    gender VARCHAR(10) NULL
);

INSERT INTO students (name, age, email, gender) VALUES
('Nguyễn Văn A', 20, 'a@gmail.com', 'Nam'),
('Trần Thị B', 21, 'b@gmail.com', 'Nữ'),
('Lê Văn C', 19, 'c@gmail.com', 'Nam'),
('Phạm Thị D', 22, 'd@gmail.com', 'Nữ'),
('Hoàng Văn E', 20, 'e@gmail.com', 'Nam');
